import { createSlice } from '@reduxjs/toolkit';
// utils
import axios from '../../utils/axios';
//
import { dispatch } from '../store';

// ----------------------------------------------------------------------

const initialState = {
    isLoading: false,
    error: null,
    alertMessage: "",
    docTypeList: [
        {
          "DocType": "2RM",
          "Description": "2nd Request For Immediate Payment",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ACV",
          "Description": "Account Voucher",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "APA",
          "Description": "Agent Pre-Alert",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44687.88888888889,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44687.88888888889
        },
        {
          "DocType": "ADC",
          "Description": "Agent's Cleared and Delivered email",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44580.67916666667,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44580.67916666667
        },
        {
          "DocType": "AIN",
          "Description": "Agents Instruction",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "AGI",
          "Description": "Agents Invoice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MBL",
          "Description": "Airway Bill/Ocean Bill of Lading",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ARN",
          "Description": "Arrival Notice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ARC",
          "Description": "Arrival Notice and Charge Sheet",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ATD",
          "Description": "Authority to Deal",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ARE",
          "Description": "Authorization Release",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BDR",
          "Description": "Bank Draft",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BRC",
          "Description": "Bank Reconciliation",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BCT",
          "Description": "Beneficiary Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BOE",
          "Description": "Bill Of Entry",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BOL",
          "Description": "Bill of Lading",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44676.779861111114,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44676.779861111114
        },
        {
          "DocType": "BOA",
          "Description": "BOM Assemble Instruction",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BOD",
          "Description": "BOM Disassemble Instruction",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BAP",
          "Description": "Booking Approved by Carrier",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44560.8875,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44564.83888888889
        },
        {
          "DocType": "BCA",
          "Description": "Booking Cartage Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BKC",
          "Description": "Booking Confirmation",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "BKG",
          "Description": "Booking Request",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CAD",
          "Description": "Cartage Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CAR",
          "Description": "Cartage Advice With Receipt",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CAT",
          "Description": "Catalog",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "COO",
          "Description": "Certificate of Origin",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "COR",
          "Description": "Certificate of Receipt",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CFS",
          "Description": "CFS Doc Receipt",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44467.05625,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44467.05625
        },
        {
          "DocType": "CHG",
          "Description": "Charge Sheet",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CLL",
          "Description": "Claim Log",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CLR",
          "Description": "Clearance",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44745.92291666667,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44745.92291666667
        },
        {
          "DocType": "APP",
          "Description": "Client Approval",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44467.044444444444,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44467.044444444444
        },
        {
          "DocType": "CDP",
          "Description": "Client Pre-Alert",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44687.88958333333,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44687.88958333333
        },
        {
          "DocType": "COL",
          "Description": "Collection Letter",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CIV",
          "Description": "Commercial Invoice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CRP",
          "Description": "Compliance Report",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "COM",
          "Description": "Compliance Tax Report",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CSD",
          "Description": "Consignment Security Declaration",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "COA",
          "Description": "Consolidation Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44682.92152777778,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44682.92152777778
        },
        {
          "DocType": "CDA",
          "Description": "Container Detention Advice",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CDR",
          "Description": "Container Detention Reminder",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CLS",
          "Description": "Container Liability Statement",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CLI",
          "Description": "Container List",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CTR",
          "Description": "Container Release",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CSS",
          "Description": "Container Summary Sheet",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "COT",
          "Description": "Cotton Certificate",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CAP",
          "Description": "Credit Application",
          "Category": "ACC",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44973.89859059028,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44973.89859059028
        },
        {
          "DocType": "CRR",
          "Description": "Credit Report",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CTP",
          "Description": "CTPAT",
          "Category": "CSR",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44543.63125,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44543.63125
        },
        {
          "DocType": "CBL",
          "Description": "Customer PU BL",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44467.05486111111,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44467.05486111111
        },
        {
          "DocType": "CAU",
          "Description": "Customs Authority",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CUS",
          "Description": "Customs Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CER",
          "Description": "Customs Error",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CUP",
          "Description": "Customs Preliminary",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "CST",
          "Description": "Customs Status Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DNB",
          "Description": "D&B Report",
          "Category": "ACC",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JT",
          "Created Time (UTC)": 44512.66527777778,
          "Last Edit": "JT",
          "Last Edited Time (UTC)": 44512.66527777778
        },
        {
          "DocType": "DGF",
          "Description": "Dangerous Goods Form",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DBN",
          "Description": "Debit Note",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44638.82638888889,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44638.82638888889
        },
        {
          "DocType": "DEC",
          "Description": "Declaration of Compliance",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DAL",
          "Description": "Delay Alert",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DLB",
          "Description": "Delivery Labels",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DOR",
          "Description": "Delivery Order",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DNO",
          "Description": "Departure Notice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DDR",
          "Description": "Direct Debit",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DIS",
          "Description": "Disbursement Note",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DRC",
          "Description": "Dock Receipt",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DOO",
          "Description": "Document of Origin",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DCF",
          "Description": "Documentary Collection Form",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DAN",
          "Description": "Documents Available Notice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DBL",
          "Description": "Draft Bill of Lading",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44675.92083333333,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44675.92083333333
        },
        {
          "DocType": "ESL",
          "Description": "EEI/SLI",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44544.785416666666,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44544.785416666666
        },
        {
          "DocType": "EFT",
          "Description": "EFT Request",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "EEI",
          "Description": "Electronic Export Information",
          "Category": "CSR",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44686.85833333333,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44686.85833333333
        },
        {
          "DocType": "EMN",
          "Description": "eManifest (CN)",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44682.92152777778,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44682.92152777778
        },
        {
          "DocType": "EPR",
          "Description": "Entry Print",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ERA",
          "Description": "Erasure Request",
          "Category": "HRE",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "EXM",
          "Description": "Examination Result",
          "Category": "HRE",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "N",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "EXM-CSR",
          "Description": "Examination Result",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "N",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ECD",
          "Description": "Exchange Control Declaration",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "EAD",
          "Description": "Export Accompanying Document",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44745.92291666667,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44745.92291666667
        },
        {
          "DocType": "EXA",
          "Description": "Export Authority",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ECA",
          "Description": "Export Cartage Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ECR",
          "Description": "Export Cartage Advice with Receipt",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ECM",
          "Description": "Export Coload Master Manifest",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ERA",
          "Description": "Export Receival Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "EXD",
          "Description": "Exporter Documents",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "FTB",
          "Description": "Final Trucker Bill",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44677.60833333333,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44677.60833333333
        },
        {
          "DocType": "FDC",
          "Description": "Food Control Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "FCR",
          "Description": "Forwarders Cargo Receipt",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44745.92291666667,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44745.92291666667
        },
        {
          "DocType": "FWI",
          "Description": "Forwarding Instruction",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "FPI",
          "Description": "FPPI",
          "Category": "CSR",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44959.85208333333,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44959.85208333333
        },
        {
          "DocType": "FUM",
          "Description": "Fumigation Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "GTP",
          "Description": "Gate Pass",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "GLJ",
          "Description": "GL Journal",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "HXD",
          "Description": "He Xiao Dan",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "HCC",
          "Description": "Health Clearance Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "HBL",
          "Description": "House Waybill/Bill of Lading",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "HAR",
          "Description": "HVLV Archived Data",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44654.936111111114,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44654.936111111114
        },
        {
          "DocType": "IDC",
          "Description": "Identification Check",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44913.972916666666,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44913.972916666666
        },
        {
          "DocType": "ICA",
          "Description": "Import Cartage Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ICR",
          "Description": "Import Cartage Advice with Receipt",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ICT",
          "Description": "Import Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44745.92291666667,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44745.92291666667
        },
        {
          "DocType": "ICM",
          "Description": "Import Coload Master Manifest",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "IEP",
          "Description": "Import/Export Permit",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "INS",
          "Description": "Insurance Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "INC",
          "Description": "Insurance Certificate",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44916.56736111111,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44916.56736111111
        },
        {
          "DocType": "INC",
          "Description": "Insurnace Certificate",
          "Category": "CSR",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44916.56805555556,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44916.56805555556
        },
        {
          "DocType": "IRT",
          "Description": "Interim Receipt",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PRV",
          "Description": "Internally Created Private Document",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PUB",
          "Description": "Internally Created Public Document",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "INV",
          "Description": "Invoice",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ILR",
          "Description": "Invoice Lines Report",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ISF",
          "Description": "ISF Form",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44467.01875,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44467.01875
        },
        {
          "DocType": "JRJ",
          "Description": "Job Revenue Journal",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "KCA",
          "Description": "Known-party Certificate of Approval",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "LBL",
          "Description": "Label",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "LCO",
          "Description": "Landed Costing",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "LET",
          "Description": "Letter",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "DEM",
          "Description": "Letter of Demand",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "LID",
          "Description": "Letter of Indemnity",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "LDL",
          "Description": "Load List",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MAN",
          "Description": "Manifest",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MDC",
          "Description": "Manufacturer's Declaration",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MSH",
          "Description": "Master House",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MCF",
          "Description": "Miscellaneous CFS Document",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MCD",
          "Description": "Miscellaneous Customs Document",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MSC",
          "Description": "Miscellaneous Document",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "N",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MFD",
          "Description": "Miscellaneous Freight Document",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MOD",
          "Description": "Miscellaneous Order Management Document",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MSD",
          "Description": "Miscellaneous Sales Manager Document",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MAD",
          "Description": "Miscellaneous Shipping Manager Document",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MVC",
          "Description": "Motor Vehicle Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "MUL",
          "Description": "Multiple Copies",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "NAF",
          "Description": "NAFTA Certificate",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ONH",
          "Description": "Onhand",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44687.888194444444,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44687.888194444444
        },
        {
          "DocType": "OBL",
          "Description": "Original Bill Of Lading",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "OUT",
          "Description": "Outturn Report",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PMP",
          "Description": "Package Manifest by Package",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PMR",
          "Description": "Package Manifest by Product",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PKD",
          "Description": "Packing Declaration",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PKL",
          "Description": "Packing List",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PPL",
          "Description": "Packing Package Label",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PIN",
          "Description": "Payables Invoice",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PPO",
          "Description": "Payables Purchase Order",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PAY",
          "Description": "Payments",
          "Category": "ACC",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PER",
          "Description": "Permit",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "POT",
          "Description": "POA-Temporary",
          "Category": "CSR",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44365.86597222222,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44365.86597222222
        },
        {
          "DocType": "POA",
          "Description": "Power of Attorney",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "POA",
          "Description": "Power of Attorney",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "POC",
          "Description": "Power of Attorney Customs",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "POC",
          "Description": "Power of Attorney Customs",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "POF",
          "Description": "Power of Attorney Forwarding",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "POF",
          "Description": "Power of Attorney Forwarding",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PAL",
          "Description": "Pre Alert",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PRT",
          "Description": "Pre-Alert",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44678.7125,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44678.7125
        },
        {
          "DocType": "PDC",
          "Description": "Prelim Commercial Docs",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44676.65833333333,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44676.65833333333
        },
        {
          "DocType": "PRS",
          "Description": "Profit Share Calculation Worksheet",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "POD",
          "Description": "Proof Of Delivery",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "RSB",
          "Description": "PTRS Reportable Small Business",
          "Category": "CTR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "QRA",
          "Description": "Quarantine Application/Coversheet",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "QRC",
          "Description": "Quarantine Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "QPK",
          "Description": "Quarantine Packing Declaration",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "QPP",
          "Description": "Quarantine Print Preview",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "QRP",
          "Description": "Quarantine Remote Print",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "QUO",
          "Description": "Quotation",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "QUO",
          "Description": "Quote",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44630.79583333333,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44630.79583333333
        },
        {
          "DocType": "QAP",
          "Description": "Quote Approved by Customer",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44559.936111111114,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44559.936111111114
        },
        {
          "DocType": "RAD",
          "Description": "Receipt of Agent Pre-Alert",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44687.88958333333,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44687.88958333333
        },
        {
          "DocType": "RCD",
          "Description": "Receipt of Client Pre-Alert",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44687.88958333333,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44687.88958333333
        },
        {
          "DocType": "RPD",
          "Description": "Recipt of Pre-DO",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44635.563888888886,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44635.563888888886
        },
        {
          "DocType": "RRA",
          "Description": "Release/Removal Authority",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "REQ",
          "Description": "Request Document",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "1RM",
          "Description": "Request for Immediate Payment",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "RQS",
          "Description": "Request for Service",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "RES",
          "Description": "Resume/CV",
          "Category": "HRE",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "SAN",
          "Description": "Sanitary Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "PSB",
          "Description": "Scan Packing Barcodes",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "SEN",
          "Description": "Security Endorsement",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44913.972916666666,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44913.972916666666
        },
        {
          "DocType": "SCR",
          "Description": "Security Screening Receipt",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44829.92361111111,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44829.92361111111
        },
        {
          "DocType": "SCR",
          "Description": "Security Screening Receipt",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44829.92361111111,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44829.92361111111
        },
        {
          "DocType": "SDR",
          "Description": "Shapiro's Doc Receipt",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44565.86111111111,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44565.86111111111
        },
        {
          "DocType": "SCI",
          "Description": "Shipco Invoice",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44635.745833333334,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44635.74652777778
        },
        {
          "DocType": "SIV",
          "Description": "ShipCo Invoice",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44677.57152777778,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44677.57152777778
        },
        {
          "DocType": "NOT",
          "Description": "Shipment Notes",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "SDN",
          "Description": "Shippers Departure Notice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "SLI",
          "Description": "Shippers Letter of Instruction",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "SAD",
          "Description": "Shipping Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "TSA",
          "Description": "Shipping Docs - TSA Warehouse",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44687.88888888889,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44687.88888888889
        },
        {
          "DocType": "SHI",
          "Description": "Shipping Instruction",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44682.92152777778,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44682.92152777778
        },
        {
          "DocType": "SHO",
          "Description": "Shipping Order",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "ANS",
          "Description": "SSL Arrival Notice",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44635.751388888886,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44635.751388888886
        },
        {
          "DocType": "SEC",
          "Description": "Staff / Group Security Documents",
          "Category": "HRE",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "SOP",
          "Description": "Standard Operating Procedure",
          "Category": "BPW",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44833.54236111111,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44833.54236111111
        },
        {
          "DocType": "SOA",
          "Description": "Statement of Account",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "SSA",
          "Description": "Steam Ship Arrival Notice",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44676.89722222222,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44676.89722222222
        },
        {
          "DocType": "SLA",
          "Description": "Steam Ship Invoice (Published)",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44677.59583333333,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44677.59583333333
        },
        {
          "DocType": "T2F",
          "Description": "T2LF Document",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44745.92291666667,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44745.92291666667
        },
        {
          "DocType": "TNC",
          "Description": "Terms and Conditions",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44973.89097222222,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44973.89097222222
        },
        {
          "DocType": "TSC",
          "Description": "Time Slot Confirmation",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "TSR",
          "Description": "Time Slot Request",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "TDM",
          "Description": "Trademark",
          "Category": "ALL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "TAD",
          "Description": "Transit Accompanying Document",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44745.92291666667,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44745.92291666667
        },
        {
          "DocType": "TCN",
          "Description": "Trucker Confirms Receipt of Doc Receipt",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JL",
          "Created Time (UTC)": 44564.9125,
          "Last Edit": "JL",
          "Last Edited Time (UTC)": 44564.9125
        },
        {
          "DocType": "RBL",
          "Description": "Trucker Receipt of BOL",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44687.8875,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44687.8875
        },
        {
          "DocType": "RTD",
          "Description": "Trucker Receipt of Pre Alert",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44943.82013888889,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44943.82013888889
        },
        {
          "DocType": "TSI",
          "Description": "TSA ID Form",
          "Category": "SCL",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44686.865277777775,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44686.865277777775
        },
        {
          "DocType": "UMR",
          "Description": "Unique Mandate Reference",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "EXV",
          "Description": "VAT/GST Exporter Exemption (AR and AP Invoicing)",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "VEN",
          "Description": "Vendor Request Form",
          "Category": "ACC",
          "System": "N",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JT",
          "Created Time (UTC)": 44469.57638888889,
          "Last Edit": "JT",
          "Last Edited Time (UTC)": 44469.57638888889
        },
        {
          "DocType": "VGM",
          "Description": "Verified Gross Container Weight",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "~BP",
          "Created Time (UTC)": 44682.92152777778,
          "Last Edit": "~BP",
          "Last Edited Time (UTC)": 44682.92152777778
        },
        {
          "DocType": "VET",
          "Description": "Veterinary Certificate",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "W-9",
          "Description": "W-9 AP",
          "Category": "ACC",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "JT",
          "Created Time (UTC)": 44469.575,
          "Last Edit": "JT",
          "Last Edited Time (UTC)": 44469.575
        },
        {
          "DocType": "WAC",
          "Description": "Warehouse Adjustment Confirmation",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WBL",
          "Description": "Warehouse Bill of Lading",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WCA",
          "Description": "Warehouse Cartage Advice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WDL",
          "Description": "Warehouse Delivery Labels",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WID",
          "Description": "Warehouse Invoice Detail",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WIC",
          "Description": "Warehouse Inwards Confirmation",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WNP",
          "Description": "Warehouse Non Picked Items",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WPL",
          "Description": "Warehouse Package Labels",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WPB",
          "Description": "Warehouse Package Labels Basic",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WPA",
          "Description": "Warehouse Packing Slip",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WIN",
          "Description": "Warehouse Periodic Invoice",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WPO",
          "Description": "Warehouse Pick Order Summary",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "Y",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WSI",
          "Description": "Warehouse Pick Shortfall Items",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WPS",
          "Description": "Warehouse Picking Slip",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WPU",
          "Description": "Warehouse Putaway Sheet",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WSS",
          "Description": "Warehouse Stocktake Sheet",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WSV",
          "Description": "Warehouse Stocktake Variance",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WTR",
          "Description": "Warehouse Transfer Confirmation",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WWO",
          "Description": "Warehouse Work Order",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WMR",
          "Description": "Weight/Measurement Report",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WTE",
          "Description": "Withholding Tax Exemption",
          "Category": "CSR",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "N",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        },
        {
          "DocType": "WCI",
          "Description": "Workers Comp Insurance Cert",
          "Category": "CSR",
          "System": "N",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N",
          "Created By": "MK0",
          "Created Time (UTC)": 44939.729166666664,
          "Last Edit": "MK0",
          "Last Edited Time (UTC)": 44939.729166666664
        },
        {
          "DocType": "WSH",
          "Description": "Worksheet",
          "Category": "SCL",
          "System": "Y",
          "Active": "Y",
          "Published": "N",
          "Update": "Y",
          "Latest": "Y",
          "Company Specific": "N",
          "Branch": "N",
          "Department": "N"
        }
      ],
};

const slice = createSlice({
    name: 'docList',
    initialState,
    reducers: {
        // START LOADING
        startLoading(state) {
            state.isLoading = true;
            state.alertMessage = "";
        },

        // HAS ERROR
        hasError(state, action) {
            state.isLoading = false;
            state.error = action.payload;
            state.alertMessage = action.payload.message;
        },
        getDocListSuccess(state, action) {
            state.alertMessage = "Document Type List Fetched";
        }
    },
});

// Reducer
export default slice.reducer;

// ----------------------------------------------------------------------

export function getDocList() {
    return async () => {
        dispatch(slice.actions.startLoading());
        try {
            dispatch(slice.actions.getDocListSuccess());
        } catch (error) {
            dispatch(slice.actions.hasError(error));
        }
    };
}


// ----------------------------------------------------------------------
